// PDF Export Service
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

export interface PDFExportOptions {
    title: string
    filename: string
    orientation?: 'portrait' | 'landscape'
}

// Simple page export - captures the main content area
export async function exportPageToPDF(title: string, filename: string): Promise<void> {
    // Find the main content area (excluding sidebar)
    const mainContent = document.querySelector('main') as HTMLElement
    if (!mainContent) {
        console.error('Main content area not found')
        return
    }

    try {
        // Create canvas from the content
        const canvas = await html2canvas(mainContent, {
            scale: 2,
            useCORS: true,
            logging: false,
            backgroundColor: '#f8fafc',
            windowWidth: mainContent.scrollWidth,
            windowHeight: mainContent.scrollHeight,
            scrollX: 0,
            scrollY: 0
        })

        // Create PDF in landscape orientation for better fit
        const pdf = new jsPDF({
            orientation: 'landscape',
            unit: 'mm',
            format: 'a4'
        })

        const pageWidth = pdf.internal.pageSize.getWidth()
        const pageHeight = pdf.internal.pageSize.getHeight()
        const margin = 10

        // Add header
        pdf.setFontSize(16)
        pdf.setFont('helvetica', 'bold')
        pdf.setTextColor(30, 41, 59)
        pdf.text(title, margin, 15)

        pdf.setFontSize(9)
        pdf.setFont('helvetica', 'normal')
        pdf.setTextColor(100, 116, 139)
        pdf.text(`Generated: ${new Date().toLocaleString()}`, margin, 21)

        // Calculate image dimensions to fit the page
        const availableWidth = pageWidth - (margin * 2)
        const availableHeight = pageHeight - 30 // Leave space for header

        const imgWidth = canvas.width
        const imgHeight = canvas.height

        // Calculate scale to fit width while maintaining aspect ratio
        const scale = availableWidth / imgWidth
        let scaledWidth = availableWidth
        let scaledHeight = imgHeight * scale

        // If height is too tall, we need to handle multi-page
        if (scaledHeight <= availableHeight) {
            // Content fits on one page
            const imgData = canvas.toDataURL('image/png')
            pdf.addImage(imgData, 'PNG', margin, 28, scaledWidth, scaledHeight)
        } else {
            // Content needs multiple pages - split by cropping the canvas
            const pxPerPage = (availableHeight / scale) // How many canvas pixels fit per page
            let currentY = 0
            let pageNum = 0

            while (currentY < imgHeight) {
                if (pageNum > 0) {
                    pdf.addPage()
                }

                // Create a temporary canvas for this page section
                const pageCanvas = document.createElement('canvas')
                const ctx = pageCanvas.getContext('2d')
                if (!ctx) break

                const sectionHeight = Math.min(pxPerPage, imgHeight - currentY)
                pageCanvas.width = imgWidth
                pageCanvas.height = sectionHeight

                // Draw the section from the original canvas
                ctx.drawImage(
                    canvas,
                    0, currentY, imgWidth, sectionHeight,  // Source
                    0, 0, imgWidth, sectionHeight           // Destination
                )

                const sectionData = pageCanvas.toDataURL('image/png')
                const sectionScaledHeight = sectionHeight * scale

                pdf.addImage(
                    sectionData, 'PNG',
                    margin,
                    pageNum === 0 ? 28 : 15,
                    scaledWidth,
                    sectionScaledHeight
                )

                currentY += sectionHeight
                pageNum++

                // Safety limit
                if (pageNum > 20) break
            }
        }

        // Add footer on last page
        pdf.setFontSize(8)
        pdf.setTextColor(148, 163, 184)
        pdf.text('Generated by Pulse Analyzer', margin, pageHeight - 5)

        // Save
        pdf.save(`${filename}.pdf`)
    } catch (error) {
        console.error('Error generating PDF:', error)
        throw error
    }
}

// Export a specific element by ID
export async function exportElementToPDF(
    elementId: string,
    options: PDFExportOptions
): Promise<void> {
    const element = document.getElementById(elementId)
    if (!element) {
        console.error(`Element with id "${elementId}" not found`)
        return
    }

    try {
        const canvas = await html2canvas(element, {
            scale: 2,
            useCORS: true,
            logging: false,
            backgroundColor: '#ffffff'
        })

        const imgData = canvas.toDataURL('image/png')
        const pdf = new jsPDF({
            orientation: options.orientation || 'landscape',
            unit: 'mm',
            format: 'a4'
        })

        const pageWidth = pdf.internal.pageSize.getWidth()
        const pageHeight = pdf.internal.pageSize.getHeight()
        const margin = 10

        // Add title
        pdf.setFontSize(18)
        pdf.setFont('helvetica', 'bold')
        pdf.text(options.title, margin, 20)

        // Add date
        pdf.setFontSize(10)
        pdf.setFont('helvetica', 'normal')
        pdf.text(`Generated: ${new Date().toLocaleDateString()}`, margin, 28)

        // Calculate image dimensions
        const imgWidth = pageWidth - (margin * 2)
        const imgHeight = (canvas.height * imgWidth) / canvas.width

        // Add image
        pdf.addImage(imgData, 'PNG', margin, 35, imgWidth, Math.min(imgHeight, pageHeight - 45))

        // Save the PDF
        pdf.save(`${options.filename}.pdf`)
    } catch (error) {
        console.error('Error generating PDF:', error)
        throw error
    }
}

// Export survey analytics report with structured data
export async function exportAnalyticsReport(
    surveyName: string,
    stats: {
        engagementScore: number
        eNPS: number
        responseRate: number
        totalResponses: number
    },
    themes: Array<{ name: string; frequency: number; sentiment: string }>,
    narratives: Array<{ type: string; title: string; content: string }>
): Promise<void> {
    const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    })

    const pageWidth = pdf.internal.pageSize.getWidth()
    const margin = 15
    let yPos = 20

    // Title
    pdf.setFontSize(22)
    pdf.setFont('helvetica', 'bold')
    pdf.setTextColor(30, 41, 59)
    pdf.text('Survey Analytics Report', margin, yPos)
    yPos += 10

    // Survey name and date
    pdf.setFontSize(14)
    pdf.setFont('helvetica', 'normal')
    pdf.setTextColor(100, 116, 139)
    pdf.text(surveyName, margin, yPos)
    yPos += 6
    pdf.setFontSize(10)
    pdf.text(`Generated: ${new Date().toLocaleDateString()}`, margin, yPos)
    yPos += 15

    // Key Metrics Section
    pdf.setFontSize(16)
    pdf.setFont('helvetica', 'bold')
    pdf.setTextColor(30, 41, 59)
    pdf.text('Key Metrics', margin, yPos)
    yPos += 10

    // Metrics boxes
    const metrics = [
        { label: 'Engagement Score', value: `${stats.engagementScore}%` },
        { label: 'eNPS', value: stats.eNPS >= 0 ? `+${stats.eNPS}` : `${stats.eNPS}` },
        { label: 'Response Rate', value: `${stats.responseRate}%` },
        { label: 'Total Responses', value: `${stats.totalResponses}` }
    ]

    const boxWidth = (pageWidth - margin * 2 - 15) / 4
    metrics.forEach((metric, i) => {
        const x = margin + (i * (boxWidth + 5))

        pdf.setFillColor(241, 245, 249)
        pdf.roundedRect(x, yPos, boxWidth, 25, 3, 3, 'F')

        pdf.setFontSize(8)
        pdf.setFont('helvetica', 'normal')
        pdf.setTextColor(100, 116, 139)
        pdf.text(metric.label, x + 5, yPos + 8)

        pdf.setFontSize(14)
        pdf.setFont('helvetica', 'bold')
        pdf.setTextColor(30, 41, 59)
        pdf.text(metric.value, x + 5, yPos + 19)
    })
    yPos += 35

    // Themes Section
    if (themes.length > 0) {
        pdf.setFontSize(16)
        pdf.setFont('helvetica', 'bold')
        pdf.setTextColor(30, 41, 59)
        pdf.text('Detected Themes', margin, yPos)
        yPos += 10

        themes.slice(0, 5).forEach(theme => {
            const color = theme.sentiment === 'positive' ? [34, 197, 94] :
                theme.sentiment === 'negative' ? [239, 68, 68] : [59, 130, 246]

            pdf.setFillColor(color[0], color[1], color[2])
            pdf.circle(margin + 3, yPos - 2, 2, 'F')

            pdf.setFontSize(11)
            pdf.setFont('helvetica', 'bold')
            pdf.setTextColor(30, 41, 59)
            pdf.text(theme.name, margin + 8, yPos)

            pdf.setFontSize(9)
            pdf.setFont('helvetica', 'normal')
            pdf.setTextColor(100, 116, 139)
            pdf.text(`${theme.frequency} mentions • ${theme.sentiment}`, margin + 8, yPos + 5)
            yPos += 12
        })
        yPos += 5
    }

    // Narratives Section
    if (narratives.length > 0) {
        pdf.setFontSize(16)
        pdf.setFont('helvetica', 'bold')
        pdf.setTextColor(30, 41, 59)
        pdf.text('Key Insights', margin, yPos)
        yPos += 10

        narratives.slice(0, 4).forEach(narrative => {
            if (yPos > 260) {
                pdf.addPage()
                yPos = 20
            }

            const typeColors: Record<string, number[]> = {
                summary: [59, 130, 246],
                positive: [34, 197, 94],
                concern: [239, 68, 68],
                action: [249, 115, 22]
            }
            const color = typeColors[narrative.type] || [100, 116, 139]

            pdf.setFillColor(color[0], color[1], color[2])
            pdf.roundedRect(margin, yPos - 4, 3, 15, 1, 1, 'F')

            pdf.setFontSize(11)
            pdf.setFont('helvetica', 'bold')
            pdf.setTextColor(30, 41, 59)
            pdf.text(narrative.title, margin + 6, yPos)

            pdf.setFontSize(9)
            pdf.setFont('helvetica', 'normal')
            pdf.setTextColor(71, 85, 105)
            const lines = pdf.splitTextToSize(narrative.content, pageWidth - margin * 2 - 10)
            pdf.text(lines.slice(0, 2), margin + 6, yPos + 5)
            yPos += 8 + (Math.min(lines.length, 2) * 4)
        })
    }

    // Footer
    pdf.setFontSize(8)
    pdf.setTextColor(148, 163, 184)
    pdf.text('Generated by Pulse Analyzer', margin, pdf.internal.pageSize.getHeight() - 10)

    pdf.save(`${surveyName.replace(/\s+/g, '_')}_report.pdf`)
}
